services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    restart: always
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_CLUSTER_NAME=link_shortener_cluster
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "SELECT * FROM system.local" ]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 30s
    networks:
      - main
    
  cassandra-initialize:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./shortener/schema.cql:/schema.cql
    command: >
      bash -c "sleep 30 &&
               cqlsh cassandra -e \"CREATE KEYSPACE IF NOT EXISTS link_shortener WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };\" &&
               cqlsh cassandra -k link_shortener -f /schema.cql"
    networks:
      - main
    
  shortener:
    build: shortener
    ports:
      - "2137:2137"
    depends_on:
      cassandra-initialize:
        condition: service_completed_successfully
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=link_shortener
    networks:
      - main
      
  getter:
    build: getter
    ports:
      - "1939:1939"
    depends_on:
      cassandra-initialize:
        condition: service_completed_successfully
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=link_shortener
    networks:
      - main
        
networks:
  main:
    
    