services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - main

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - main

  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    ports:
      - "9042:9042"
    restart: always
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_CLUSTER_NAME=link_shortener_cluster
      - CASSANDRA_SEEDS=cassandra-1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "SELECT * FROM system.local" ]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 30s
    networks:
      - main
    
  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    ports:
      - "9043:9042"
    restart: always
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_CLUSTER_NAME=link_shortener_cluster
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-1:
        condition: service_healthy
    networks:
      - main
      
  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3
    ports:
      - "9044:9042"
    restart: always
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_CLUSTER_NAME=link_shortener_cluster
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-2:
        condition: service_started
    networks:
      - main
    
  shortener:
    build: shortener
    ports:
      - "2137:2137"
    depends_on:
      cassandra-1:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=link_shortener
      - KAFKA_BROKER=kafka:29092
    networks:
      - main
      
  getter:
    build: getter
    ports:
      - "1939:1939"
    depends_on:
      cassandra-1:
        condition: service_healthy
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=link_shortener
    networks:
      - main
      
  cleaner:
    build: cleaner
    depends_on:
      cassandra-1:
        condition: service_healthy
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=link_shortener
      - TTL_SECONDS=120
      - CLEANUP_INTERVAL_MS=60000
    networks:
      - main
        
networks:
  main:
    
    